이슈 댓글 기능 구현
lsj135779/givemetuna pull request #12
Opened 2023-12-31 01:13 UTC by vanillacake369

- [ ] 댓글 생성
- [ ] 댓글 수정
- [ ] 댓글 삭제
- [ ] 댓글 리스트 조회

2023-12-31 07:49 UTC, BMDK9 requested changes
굿입니당

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/card/entity/Card.java
> +@EqualsAndHashCode(of = "id", callSuper = false)
이거 뭐에요? 그냥 단순히 기능을 몰라서 궁금해서 여쭤봅니다.

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/cud/IssueDeleteResponseDto.java
> +@AllArgsConstructor(access = AccessLevel.PACKAGE)
@NoArgsConstructor @AllArgsConstructor

어떤 이유로 두 개를 다 다셨는지 궁금합니다!

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/cud/IssueUpdateRequestDto.java
> +@Builder
RequestDto에 빌더를 달면 어떤 경우에 사용을 하는거에요? 궁금합니다.

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/read/IssueReadResponseDto.java
> +@EqualsAndHashCode
이거 뭐에요?? 모르는 거에요! 가르쳐주세요!

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/read/IssueReadResponseDto.java
> +	@QueryProjection
이것도 알려주세요

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/read/IssueSingularReadRequestDto.java
> +
이 클래스는 작성 중 이신거죠???

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/entity/Issue.java
> +@DynamicUpdate
'왠'만하면 좀 알려주세요

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/entity/Issue.java
> +@ToString
이것도 알려줘용

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/entity/Issue.java
> +	@Nonnull
이건 어떤 역할을 하는 친구입니까?

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/entity/Issue.java
>  	@Enumerated(EnumType.STRING)
구우우웃~

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/repository/IssueRepositoryCustomImpl.java
> +			.leftJoin(issue.issueComments, issueComment) // fetch join of "issue" & "card"
innerJoin 대신 leftJoin을 사용하신 이유가 있을까요??

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/repository/helper/IssueQueryOrderFactory.java
> +					}
default 경우는 어떻게 페이징 돼서  나오는 건가요?

향상된 switch문을 사용하시지 않은 이유가 있을까요?

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/repository/helper/IssueQueryOrderFactory.java
> +	 */
출처 표시하는 거에요???

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/repository/helper/IssueQueryOrderFactory.java
> +	 * @author 임지훈
우와 펜입니다. '왠'만하면 싸인 한 장 부탁드려요.

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/service/read/IssueReadServiceImpl.java
> +public class IssueReadServiceImpl implements IssueReadService {
어떤 의도로 서비스를 인터페이스로 구현하셨는지 궁금합니다.

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issue/service/search/IssueSearchService.java
> +
이부분도 구현 중이신거죠?

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/controller/cud/IssueCommentCudController.java
> +@EnableWebMvc
사용하신 이유를 알려주세요 궁금해요

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/dto/cud/IssueCommentDeleteRequestDto.java
> +
작성 중이 신거죠?

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/dto/cud/IssueCommentDeleteResponseDto.java
> +
작성 중 이신거죠?

2023-12-31 07:49 UTC, BMDK9 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/service/read/IssueCommentReadService.java
> +
작성 중 이신거죠?

2023-12-31 10:00 UTC, tpgns4283 approved these changes
엄청 열심히 하셨네요.. 보고 배울 점이 많은 거 같아요. 고생하셨습니다.

2024-01-01 07:02 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/card/entity/Card.java
> +@EqualsAndHashCode(of = "id", callSuper = false)
같은 엔티티인지 확인하기 위해 id 값으로 확인하는 기능입니다!

2024-01-01 07:02 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/cud/IssueDeleteResponseDto.java
> +@AllArgsConstructor(access = AccessLevel.PACKAGE)
PACKAGE로 가둠으로서 정적 메소드 이외의 메소드로 인스턴스 생성을 막기 위함입니다.

2024-01-01 07:03 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/cud/IssueUpdateRequestDto.java
> +@Builder
테스트 시, 빌더를 통해 값을 지정해줄 수 있습니다.

2024-01-01 07:03 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issue/dto/read/IssueReadResponseDto.java
> +	@QueryProjection
QueryDsl을 사용 시, dto로 변환해주는 어노테이션입니다.

2024-01-01 07:04 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issue/service/search/IssueSearchService.java
> +
해당 부분은 금일(01-01) 내에 구현 중에 있습니다 ㅠㅠ

2024-01-01 07:04 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/dto/cud/IssueCommentDeleteRequestDto.java
> +
필요없어서 삭제했어요 ㅎㅎ

2024-01-01 07:04 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/issuecomment/controller/cud/IssueCommentCudController.java
> +@EnableWebMvc
https://goodgid.github.io/Spring-Enable-MVC-Annotation/

2024-01-01 07:14 UTC, merged