Feature seungjun
lsj135779/givemetuna pull request #13
Opened 2023-12-31 03:58 UTC by lsj135779

체크리스트 권한 검증 추가
체크리스트 칼럼 추가
체크리스트 첫 번째 생성 메서드 추가

2023-12-31 07:00 UTC, vanillacake369 requested changes
몇 가지 부분 이외에는 주석처리도 잘 해주셨고 고생많으셨네영!!

제가 요청드린 부분은 1,2가지 이외 부가적인 부분이라 신경 안 써주셔도 됩니다!
편하신대로 바꿔주시고 올려주세요~!

2023-12-31 07:00 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/checklist/controller/ChecklistController.java
> +		}
추후에 try-catch문을 쓰지 않으시게끔 도메인 별 예외클래스 짜겠습니다!
도메인 별 예외클래스로 처리해주세요~~! @lsj135779

2023-12-31 07:00 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/checklist/controller/ChecklistController.java
> +				card_id, userDetails.getUser());
> http header값이나 uri 값에 대한 검증 :: Controller 단에서 검증 => 다른 도메인 검증 시, Controller가 다른 도메인 서비스 의존하게 변경
> 
> http body값이나 uri 값이 로직이랑 밀접한 검증 :: Service 단에서 검증
> 
> 검증을 분리의 이점 :: 위치에 따라 검증을 분리해줄 수 있음
> 리팩토링이 하기 편하지 않나

위 내용과 같이, `stageId`,`boardId`,`cardId`에 대한 검증은 각각의 도메인 서비스를 의존하여 컨트롤러에서 검증해도 되지 않나 싶습니다!

2023-12-31 07:00 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/checklist/service/ChecklistService.java
> +//		}
해당 부분은 메서드로 추출할 수 있지 않나 싶습니다!!
웬만하면 지금 너무 급해서 코드 스타일 이야기는 하고 싶지 않은데,,, 
해당 부분이 중복되어서 나중에 리팩토링 할 때 힘들 거 같아서요!! 😅😅

2023-12-31 07:00 UTC, vanillacake369 commented on src/main/java/com/sparta/givemetuna/domain/checklist/service/ChecklistService.java
>  		Long cardId, User user) {
각 서비스 메서드 별로 어떤 Exception들이 발생할 수 있는지 throws문을 통해서 명시해주시면 좋을 거 같아요!

이건 제가 도메인 예외 클래스를 만들어드리면 같이 한 번 해보아요!

2023-12-31 07:00 UTC, BMDK9 approved these changes
좋습니다~

2024-01-01 07:07 UTC, vanillacake369 approved these changes

2024-01-01 07:17 UTC, merged